### ISSUE TITLE
We need a standard naming convention for our individual and aggregate metrics

### ISSUE THREAD

**Issue by klumb** [chaoss/metrics#105]
I am going through the metrics markdown files and finding a lot of repetition. I would like to push a fix that will allow us to get these pages up to date and easier to work with.

Besides some basic editing, I think we need to agree on a standard naming convention for these files. I propose:
"the name of the resource being measured"-"more_description_if_necessary"- "the_measurement_if_necessary".md

Ex:
issues-open-average_time_distribution.md

This example metric describes the average number of issues over a period of time.

By doing this we can easily sort and identify related metrics.  

Thoughts?

**Comment by GeorgLink** [comment]
That proposal may have the result that we create a separate page for each
display and way to look at a metrics. In the past we discussed that we
could consolidate the metrics page to the core data point and then include
within the detail page how the data can be aggregated and displayed.

Counter proposal: issues.md
Sub-section on the page: Visualization
sub-sub-section: Average
sub-sub-section: time analysis

**Comment by klumb** [comment]
@GeorgLink that could work but how would we handle building recipes for aggregate metrics?

@sgoggins, what are your thoughts on this. What would be useful for Augur?

**Comment by GeorgLink** [comment]
I guess that aggregate metrics that combine multiple datapoints would need
a unique page and link out to the underlying datapoints.

**Comment by jgbarah** [comment]
I wonder if we could have this discussion in the chaoss/wg-gmd repository, test it there, and then propagate it to the rest of the metrics.

Please remember that in that repo, we're working on a complete new version of GMD metrics, and any work here could be difficult to merge later...

What do you think?

**Comment by GeorgLink** [comment]
I think that would work well for GMD metrics. The list Kevin works on goes
beyond that and needs a lot cleaning up.

I think D&I is also interested in the metric naming convention right now.

**Comment by klumb** [comment]
Sure, i think it makes sense to discuss it in 
GMD. I am wondering if GMD needs a slightly different structure than what D&I is using.  I think GMD tooling is perhaps in a place where they can consume these metrics right now so the question of how you want them served is important but I do think we need some basic structure for how all the metrics are represented.

**Comment by sgoggins** [comment]
I think this discussion is a little bit afield from the root goals right now.  What we are talking about is a hierarchy.  "Goal" is merely a naming convention within the hierarchy, under which detailed metrics exist. For GMD, I think "Understanding Issues" is a "Goal".  "Open Issues", "Closed Issues", etc. exist under that main goal.  We've had numerous discussions about the meaning of a "commit"; we surely would not put **every** possible way of considering commits into a single metric. Or maybe we would ... but that's not something to be discussed abstractly and a priori getting the temperature of the GMD working group.  Right now the "alignment" effort happening here  feels a wee bit heavy handed. :)  ... I thought my point on the weekly call a couple days ago was generally agreed with: That the GMD group would need to figure out the "Goal" classification and subsequent hierarchies on its own. I agree with @jgbarah that this is something the GMD group can work through, with the GOAL (ha ha) of aligning with the D&I group's general structure.

**Comment by klumb** [comment]
Okay, moving the discussion of naming convention to GMD.
