### ISSUE TITLE
Maintainability: Clear Code and Clean Code

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/metrics#109]
I'm not sure if this could be D&I or Risk or Value (or all of the above).

Maintainability:
> If a stranger can modify your code and fix a bug in less than an hour, it is maintainable. 

> Test it. Ask someone who is outside of the project to take a look at your code and tell you how clear it is. Not how beautiful your classes and code constructs are—that’s what makes it clean. Instead, ask someone to fix a bug in just 30 minutes and see how they react. You will realize how clear the code is and whether it speaks the language a stranger can understand.

Full reference: https://www.yegor256.com/2018/09/12/clear-code.html

**Comment by GeorgLink** [comment]
Posted on D&I workgroup: chaoss/wg-diversity-inclusion#74

**Comment by germonprez** [comment]
Closing here as posted to D&I
