### ISSUE TITLE
Diversity & Inclusion File

### ISSUE THREAD

**Issue by emmairwin** [chaoss/metrics#114]
https://github.com/chaoss/metrics/blob/master/1_Diversity-Inclusion.md

This file should redirect to our repo.  Unless there is a reason for this I am not aware of?  cc / @GeorgLink

**Comment by GeorgLink** [comment]
I agree on linking to our repository.

I would like to find a way to keep the metrics we have in that file right now. They emerged from a session we did last year at the OSS NA in LA and I believe these to be relevant to many people. 

proposed TODO: make sure the metrics in the D&I chaoss/metrics repository appear in the chaoss/wg-diversity-inclusion repository before we remove them and create the link.

**Comment by germonprez** [comment]
Is the suggestion to essentially archive this page (for posterity and to not lose this information)? And when someone clicks on the D&I link they are taken to the WG page?

**Comment by GeorgLink** [comment]
What could be the benefit of keeping the current metrics separate?

I envision to merge the current metrics with the new files in the D&I repo.
The git history could be the archive.

**Comment by jgbarah** [comment]
> The git history could be the archive.

I agree with that.

WRT the redirection, or link, I would rather consider the following approach:

* For now, the current file is keep as such, with a prominent link at the top stating that the D&I working group is working on a new version, welcoming anyone to participate, and linking to the D&I repo.
* When the D&I working group considers it appropriate, they propose the new metrics the group is producing to be dumped in this metrics repo, substituting this file with a new version (or directly upload the new files, as we define)

I would like to have a similar procedure for GMD and other working groups: link in the corresponding file to the wg repository, work in the wg repo to produce a new version of the metrics, upload new versions of the file (and metrics) to the metrics repo when the wg decides they want to "release".

What do you think?

**Comment by GeorgLink** [comment]
We have decided to depricate the chaoss/metrics repository. The solution is to post on the CHAOSS website metrics as determined by the workgroups.

The above mentioned page is currently under review by the D&I Workgroup (chaoss/wg-diversity-inclusion#143).

**Comment by jgbarah** [comment]
According to the [procedure recently approved](https://github.com/chaoss/governance/blob/master/CONTRIBUTING.md#how-do-we-make-decisions), I think this could be considered as a proposal based on a perceived consensus. @GeorgLink maybe it could make sense to send the proposal to the CHAOSS mailing list, since it is a major change. What do you think? (I can send the message if you want).

**Comment by GeorgLink** [comment]
Good idea. The proposal to depricate the chaoss/metrics repo is already sent to the CHAOSS mailing list as part of last weeks meeting minutes. If I missed something or that is not enough, please feel free to post an email to the list.

**Comment by jgbarah** [comment]
Oooops. You're completely right. Sorry for not noticing it was in the minutes.

In that case, could we close this issue?

**Comment by GeorgLink** [comment]
I would leave it open until the D&I category page is replaced.

**Comment by GeorgLink** [comment]
The page in question no longer exists and a link to the D&I WG repo exists on the README.md
