### ISSUE TITLE
Deprecating the Metrics Repository

### ISSUE THREAD

**Issue by germonprez** [chaoss/metrics#117]
During the last board meeting and monthly CHAOSS meeting, we decided to deprecate the metrics repository. There is good information in here that needs to be retained but I 100% agree that the metrics repository is not the place for maintaining canonical metrics lists, reflecting the work going on in D&I and GMD. 

So, I propose: 

1) https://chaoss.community/metrics/ gets updated to directly point to the work group lists (i.e. focus areas)
2) The metrics repository simply becomes the Activity Metrics List - this will allow us to capture new metrics without creating unnecessary noise in the work groups. 
3) We only keep the metric name and description -- the detail behind (known implementations; visuals) is simply too difficult to maintain and keep updated.

**Comment by jgbarah** [comment]
I would start by writing in a larg font, in the main README.md file for the repository "THIS IS A DEPRECATED REPOSITORY MOVED TO CHAOSS ATTIC", or something like that. Below, we could have some text along the lines of "We're keeping this repository for historic reasons, and to preserve its contents for future use, but no new updates will be done. Issues and pull requests will be ignored."

If you find it reasonable, I can produce a pull request for this.

**Comment by GeorgLink** [comment]
During today's meeting, I got the sense that the repository will continue to have an active role in the metrics work. We will clean up the repo, link to the workgroups, and have a list of all metrics as the central element within the repo.

**Comment by GeorgLink** [comment]
so: not depreciating the Metrics Repository

**Comment by germonprez** [comment]
Correct
