### ISSUE TITLE
Cross check metrics with workgroups

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/metrics#120]
We now have a new Readme. The next step is to add a new column that indicates in what workgroup the metric is advanced. New workgroup metrics may have to be added to this list.

Prototype:

|Metric|Description|Workgroup|
|---|---|---|
|  |  | D&I |
|  |  | GMD |
|  |  | D&I; GMD |

**Comment by GeorgLink** [comment]
Note Difference: The metrics list uses 'Description' but the metrics in the workgroups use 'questions'.

**Comment by germonprez** [comment]
Done
