### ISSUE TITLE
Infrastructure for releasing CHAOSS metrics

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/metrics#125]
The proposed infrastructure for releasing CHAOSS metrics has two components:

1) **Index page of release metrics**
  - https://chaoss.community/metrics
  - manually curated markdown file in chaoss/website
  - Templated through WordPress
  - list of: metric name, link to specification on WG GHpage
  - Note at the beginning that our aim is to routinely publish metrics via working groups and that implementation of those metrics in tooling being developed will be an important consideration for what is published and worked on. We want to deliver not only metrics definitions but ways that people can examine those metrics.

2) **Templated specification pages in WG repos**
  - Each WG repo has same template, GHpages
  - Subdomain, e.g. https://gmd.chaoss.community/
  - In addition to released metrics pages, WGs can publish additional pages by defining what gets published through a settings file

To-Do's:
- [ ] AI Georg, Tobie: develop template for repo pages
- [ ] AI CHAOSS community: determine sub-domain name for WG's (e.g., gmd.chaoss.community, di.chaoss.community, common.chaoss.community)
- [ ] AI WGs: determine metrics for release
- [ ] AI Kevin: change https://chaoss.community/metrics

**Comment by GeorgLink** [comment]
Update 2019-02-12, CHAOSS weekly call:

- Above proposed solution would not allow for versions because it reflects the most current work in the Working Groups.
- To have versions with above solutions requires WG to change their workflows (not work in master or create a release directory).

Alternative solution could be to have the metric pages directly within the website and not generated from the WG repositories.
- Benefit: template is always in sync with website
- Does not change WG workflow
- Requires new pages to be created in wordpress for each new metric
- Continues to allow us to update via pull requests to the website repo.

**Comment by geekygirldawn** [comment]
The next step as discussed in the call is to bring this to the Governing board for a decision about whether we want to do rolling releases or periodic releases, and if so, how often do we want to do a release. We also need to better understand any technical implications of this decision before we get to the governing board meeting.

**Comment by GeorgLink** [comment]
Based on discussions so far, Kevin and I created a new proposal. Here is a summary so far:

# CHAOSS Metrics Release Infrastructure Proposals

## Proposal 1: List on Website; Metrics on GHPages

Developed by: Tobie Langel, Sean Goggins, Matt Germonprez, Georg Link

The proposed infrastructure for releasing CHAOSS metrics has two components:

**1. Index page of released metrics on website**
*   https://chaoss.community/metrics
*   manually curated markdown file in chaoss/website
*   Templated through WordPress
*   list of: metric name, link to specification on WG GHpage
*   Note at the beginning that our aim is to routinely publish metrics via working groups and that implementation of those metrics in tooling being developed will be an important consideration for what is published and worked on. We want to deliver not only metrics definitions but ways that people can examine those metrics.

**2. Templated metric detail pages in WG repos**
*   Each WG repo has same template, GHpages
*   Subdomain, e.g. https://gmd.chaoss.community/
*   In addition to released metrics pages, WGs can publish additional pages by defining what gets published through a settings file

Benefits:
*   Avoid duplication of metric detail pages
*   Updates to metrics are automatically published
*   Releasing new metrics can be done through pull requests against markdown files, no changes to website needed

Concerns:
*   Continuous release, no stable version, unless working groups start using branches

## Proposal 2: Everything on Website

Developed by: Kevin Lumbard, Georg Link

The proposed infrastructure for releasing CHAOSS metrics has two components:

**1. Release folder in chaoss/metrics repository**
*   https://github.com/chaoss/metrics/
*   Manually copy "released" metrics to a dedicated folder; subfolder can be named after version number (e.g., chaoss/metrics/released/v201903/ )
*   Templated through WordPress (next item)
*   list of: metric name, link to pages on WordPress

**2. All metric pages on website**
*   Entry point: https://chaoss.community/metrics
*   Each metric gets its own website page
*   WordPress pulls the "released" metrics from repository into website
*   Requires manual editing in Wordpress for each release because the path to the markdown files changes.

Benefits:
*   Version history visible in repository without going through git history
*   Templating is consistent through website

Concerns:
*   Duplication of metric detail pages, danger of developing against older versions
*   Manual extra work to create website pages for each release for each metric

**Comment by tobie** [comment]
So regardless of the implementation details of the two proposals, the key difference is whether we're pointing to a "living standard" or a versioned one.

I brought up my experience from the Web standardization space in a previous call already, but to summarize it: the Web moved from a versioned model to a living standard one, essentially as software development practices changed from shipping software on CDs in cardboard boxes to brick and mortar stores to being instantly deployed over the internet multiple times per day.

In the process we gained agility, tightened the feedback loop between implementors and spec editors, interoperability between different implementations and clarity for end users.

Before making a decision on this topic, I think **we ought to hear from the different implementors** to understand, in versioned model, whether they'd be implementing from the previous version, or working with the editors of the upcoming version to ship a bleeding edge implementation. If the latter is the case, I urge you to learn from our mistakes and not create the overhead of multi-version solution. For an example of that, try to find which specification browser vendors are implementing of the `XMLHttpRequest` specification and compare that with the WHATWG `fetch` API. (The first is versioned, the second one isn't, and there's been a multi-year effort to fix SEO of the former to make it more obvious.)

Once we have that clarified I suggest going for whatever implementation requires the least manual work on a daily basis, because every point of friction is going to hurt the ability to ship.

**Comment by germonprez** [comment]
Thanks for the succinct overview @tobie

**Comment by GeorgLink** [comment]
## Proposal 3: Everything on Website from WG repos
Developed by: Kevin Lumbard, Sean Goggins, Jesus , Matt Germonprez, Georg Link

The proposed infrastructure for releasing CHAOSS metrics has two components:

**1. Release from commit within each WG**
- Each WG determines which focus areas and associated metrics are ready for release and dedicates a specific commit using GitHub releases (basically, tagging a commit).
- Templated through WordPress (next item)

**2. All metric pages on website**
- Entry point: https://chaoss.community/metrics
  - list of: focus area, metric name, link to pages on WordPress
- Each metric gets its own website page
- WordPress pulls the “released” metrics from repository and “release” commit into website
- Requires manual editing in Wordpress for each release because the path to the markdown files changes.

Benefits:
- Release commits could be labeled as “release” in GitHub, history is visible
- Templating is consistent through website
- Limit duplication of metric detail pages to website vs. repository
Concerns:
- Manual extra work to create website pages for each release for each metric

**Comment by GeorgLink** [comment]
> So regardless of the implementation details of the two proposals, the key difference is whether we're pointing to a "living standard" or a versioned one.

Thanks, @tobie.  

Proposal 3 is a middle ground between Proposal 1 and 2. It can easily be adapted to point to the "living standard" or an unchanging commit version of the standard. 

Whether we have a living standard or a unchanging release version is still being debated.

**Comment by tobie** [comment]
If you have a different URL per version, as I understand is the case for proposal 3, how will you know that the page you navigated to is actually the most recent and latest version of the spec?

Imagine version 1 receives a lot of Google juice and version 2 doesn't as much. Googling for the metric will point everyone to version 1.

Similarly, imagine you've bookmarked version 1 in your browser, how will you find out it's no longer the canonical version?

**Comment by GeorgLink** [comment]
> If you have a different URL per version, as I understand is the case for proposal 3, how will you know that the page you navigated to is actually the most recent and latest version of the spec?

What if we modified this to only have the most recent released version on the website. If anyone wants to see older versions, they have to go to the repository but will not find it on the website?

**Comment by tobie** [comment]
> What if we modified this to only have the most recent released version on the website. If anyone wants to see older versions, they have to go to the repository but will not find it on the website?

So more specifically, what does this mean?

1. Do you just 404 and now have a broken link to the spec, thus breaking any reference to the metric in documentation, papers, etc.?
2. Do you permanently redirect the old link to the latest spec, thus creating a living standard in disguise?
3. Do you keep the old link around but add a huge deprecated sign to it, thus adding more friction and error surface area to the publishing process?

**Comment by GeorgLink** [comment]
> So more specifically, what does this mean?

@tobie, excellent questions. I am glad you are helping us think through these issues. Here are my thoughts:

1. I don't like breaking links. 

2. Instead of forwarding, can we recycle the url's for the same but updated metrics? It is not a living standard in the sense that every change on GitHub is reflected on the website; but it has living standard characteristics in that there is no older version on the website. For permalinks to a specific version we could point to the repository, like we have in the prototype that @klumb posted to the mailing list.

3. If we recycle URLs for updated metrics, then we only need to keep around depreciated metrics, or when we change naming conventions. I go back to the idea of requesting that permalinks point to a specific commit in the repositories.

**Comment by GeorgLink** [comment]
Here is the email content @klumb had posted to the mailing list on Wed, Feb 20:

> Hey everybody,
> 
> Georg and I prototyped the metrics release on the website.
> 
> Please take a look.
> 
> https://chaoss.community/metrics-rc/
> 
> https://chaoss.community/metric-1-rc/
> 
> https://chaoss.community/metric-2-rc/
> 
> This is based on Proposal 3 from the earlier discussion. 
> 
> This release process is not automated but it is fairly easy and can be quickly to implemented. 
> 
> 
> Cheers, 
> 
> 
> Kevin Lumbard (he/him/his)
> University of Nebraska at Omaha
> PKI 367

**Comment by jgbarah** [comment]
> If you have a different URL per version, as I understand is the case for proposal 3, how will you know that the page you navigated to is actually the most recent and latest version of the spec?

We can use the strategy they use in the Python manual: in all the pages, there is a menu linking to the same page in all versions. See the top of https://docs.python.org/3/library/persistence.html for example

I think this could be automated, and we could have even warnings like "this is an old version of the metric". we can also have tags like "latest", if needed.

In any case, at least for the near future, maybe this is not a big problem, and maybe is something that we can start to thnik about after the first release...

**Comment by tobie** [comment]
I’m not suggesting there aren’t solutions to these issues. Just that they require quite a bit of infrastructure, automation, and processes, that I’m not sure we have the resources for.

**Comment by jgbarah** [comment]
Oh, i see, @tobie, thanks!

But then, what do you propose? i feel we need to have versioning, since a given implementation should be able of saying "I'm implementing all of CHAOSS metrics vX.Y.Z", or for a discussión, we should be able of referring to "Metric M, as defined in CHAOSS metrics vX.Y.Z". And if we have this, we need a way of "releasing".

Maybe we could have just a link from "latest" to the latest release, and ensure as much as possible that for links meant to be permanent, we always use the "latest" one? Any other idea?

**Comment by GeorgLink** [comment]
> Maybe we could have just a link from "latest" to the latest release, and ensure as much as possible that for links meant to be permanent, we always use the "latest" one? Any other idea?

@jgbarah how would you feel about permalinks pointing to a specific commit in our repositories. The website would not be a permanent place for all versions but only be to present the most recent release in a pretty template. -- This allows implementations to reference the exact specification without worrying the URL will go away, unless GitHub goes away.

**Comment by tobie** [comment]
> "I'm implementing all of CHAOSS metrics vX.Y.Z"

Oh, so you’re suggesting a versioning at the global level, not at the spec level?

I don’t think there’s consensus as to what’s needed, here. I think that’s what we should be talking about first.

**Comment by rpaik** [comment]
What would be the benefit of having a "versioned" metrics?  For people coming from outside, not sure how many will necessarily want to dig into older "versions" of metrics vs. simply wanting guidance on what type of metrics (or implementations) they need to consider for Diversity & Inclusion, GMD, etc.

**Comment by geekygirldawn** [comment]
Before we can decide on a technical solution, we need to make a decision about whether we want versioned metrics or not. The plan is to make this decision at the CHAOSS Governing Board Meeting at OSLS.

**Comment by tobie** [comment]
What would be good, would be to hear from the different stakeholders beforehand.

I'd love to know whether implementors are planning to implement a specific version of a metric or work from the latest version. And if they're going to work from a specific version, will they do that on a per metric basis or with a metric at the WG or CHAOSS level.

Similarly, I'd super curious as to how researchers would work with this material, and how OSPOs think about this.

**Comment by jsmanrique** [comment]
Wow! It's being a long thread... First of all, I agree we need some kind of _metrics reference_ or infrastructure for people outside CHAOSS, and even for ourselves. 

From my quick reading point of view it seems we are mixing "the what" (we need a list of metrics discussed by CHAOSS) with "the how" (GH pages, Wordpress, etc.). I think our "tech" minds are playing against us. The most simple solutions are usually the best in these cases. The idea of having a [template](https://github.com/chaoss/metrics/blob/master/activity-metrics/metric-template.md) is a great starting point.

Then, having WG is another great thing to have _topics_ to group metrics or to tag them, but I like the idea of the metrics being all in one repo (this one!). So _everyone_ could come here and check "what CHAOSS metrics are". Having said that, I think the current list (the README) needs some cleaning and it can generates some confusion to newcomers.

I might be a bit biased from my experience in W3C (I know your pain @tobie). Versioning metrics is something I would not recommend, and from _implementator_ point of view it generates more stress in terms of "should I implement the _unstable_ metric and be innovative (Google-like way of life) or should I implement the _stable_ one and be considered _old school_ (Microsoft-like way of life)?". What would you do? How long do you think an _stable_ metric would last? Do you want to walk the "overhead" of discussing this is _stable_ this is _unstable_?

**Comment by germonprez** [comment]
I'm going to close this as we now have a nice method to the release of metrics. We may want to document in (outside of this Issue) to capture exactly how we are doing things.
