### ISSUE TITLE
Common Metrics repository README and other documents

### ISSUE THREAD

**Issue by klumb** [chaoss/metrics#138]
Question: Is the common metrics work group going to continue to work out of the metrics repository or will it be getting its own repository?

Regardless of the answer, can we create a README.md for the group that I can link to from the website.

Additionally, it would be nice to have some documented processes for how to contribute. 

I like the idea of keeping it in the metrics repository but how it is structured within the repository probably needs some discussion.

**Comment by jgbarah** [comment]
Current practice is that every working group works in their own repo.

However, the use of this metrics repo has never been set in stone, I think. If the Common Metrics wg prefers to work in this repo, I see no problem. i would only rename the repo to "wg-common" or something like that, to aling with other working groups.

**Comment by germonprez** [comment]
The problem is that it contains all metrics across all working groups.

**Comment by jgbarah** [comment]
I see. In that case, having a specific repo would be much better, right?

**Comment by GeorgLink** [comment]
The Common Metrics WG  now has its own repo: https://github.com/chaoss/wg-common
