### ISSUE TITLE
New Metrics: Support of source code related metrics

### ISSUE THREAD

**Issue by inishchith** [chaoss/metrics#139]
After the ideation of adding support to GrimoireLab to produce `source code related metrics` using [Graal](https://github.com/chaoss/grimoirelab-graal) was introduced in https://github.com/chaoss/grimoirelab/issues/182 and supporting discussion thread https://github.com/chaoss/grimoirelab/issues/182#issuecomment-476267563 and a response https://github.com/chaoss/grimoirelab/issues/182#issuecomment-476327190. I had some thoughts to get the discussion started here in order to understand the current state and future scope of additions of metrics.

------------------------
Some of the ideas aligned were:

1. **License & Copyright analysis related**
      - `All licenses`: List of licenses present in the repository.
      - `License Count`: Number of licenses found in a software repository.
      - `Package License Declaration`: A list of license declarations on the software
package.
      - `Copyright Declaration`: The degree to which the project properly declares
copyright details.
      - `License Coverage`: Number of files with a file notice (copyright notice + license
notice) and ones without a file notice.

2. **Code complexity analysis related ( cyclomatic complexity, LOC )**
      - `LOC`: Total Lines of Code
      - `CCN`: Cyclomatic Code Complexity of a software repository.
      - `Complex Files`: A list of files with higher complexity in terms of Cyclomatic Code
Complexity (CCN) & Lines of Code (LOC).
      - `Functions`: Number of functions
      - `Comments`: Total comment lines present in the repository.

Would like to know if this is the right place for the discussion.
I'd be more than happy to join a call for the discussion :)
Would also like to have some pointers from @jgbarah @valeriocos @aswanipranjal

Thanks

**Comment by valeriocos** [comment]
Thank you @inishchith for triggering the discussions about code related metrics. Overall they look OK, find below some comments for each idea.

> 1. License & Copyright analysis related

Possible additions to the proposed list could be:
- the list of files without a license (this could be useful to drive improvements to increase the license coverage)
- `License Coverage` at package/folder level

> 2. Code complexity analysis related ( cyclomatic complexity, LOC )

It could be interesting to apply the same metrics also at package level. This info could be useful to drive refactorings.

**Comment by inishchith** [comment]
@valeriocos Thanks for suggesting the improvements, Overall I like the ideas. We can prioritize their implementation accordingly. I'll update the thread in case of refinements to the initially suggested ideas.
I'm unsure how we proceed from here. 

@GeorgLink Can you have a look 

Thanks.

**Comment by jgbarah** [comment]
I like the idea, but I'm not sure how to convey it. We have some working groups potentially involved... Maybe the best thing could be one of these:

* Deal with these metrics in the context of the Evolution (formerly GMD) working group, likely in the context of the code development focus area.

* Deal with these metrics here, and then each wg can decide which ones to pick up for their focus areas...

@germonprez @GeorgLink any feedback about this?

**Comment by GeorgLink** [comment]
Thanks @inishchith for kicking off the discussion.

I agree with @jgbarah, any WG can pick up a metric they are interested in.

The Common, Risk, or Evolution Working Groups are good places to advance these metrics. I suggest you see which WG is most interested and advance the metrics there.

**Comment by inishchith** [comment]
@jgbarah @GeorgLink Thanks for the suggestions :)
I'd like to get involved with the discussion for the same in case it's conducted in the weekly meetings if possible. I'm unaware of the schedule of the meetings though. Please do let me know.

Thanks

**Comment by GeorgLink** [comment]
Schedule of meetings: https://chaoss.community/participate/

Please let me know if you have any questions about the meetings or the page I directed you to.

**Comment by inishchith** [comment]
@GeorgLink Thanks for the response. 
I'll surely try and join the upcoming meeting in some time :)

**Comment by germonprez** [comment]
Issue resolved.
