### ISSUE TITLE
Template links to missing file

### ISSUE THREAD

**Issue by mbbroberg** [chaoss/metrics#174]
In [metric-template.md](https://github.com/chaoss/metrics/blob/master/activity-metrics/metric-template.md), it reads: 

> ```The first few sentences should match the description in the [metrics list](../activity-metrics-list.md).```

That file no longer exists. Is there a new location for that information or can we offer a short description of the goal in that file?

**Comment by germonprez** [comment]
Good catch @mbbroberg. I just put in a PR to fix this. Until then, the list is here: 

https://github.com/chaoss/metrics/tree/master/activity-metrics

**Comment by GeorgLink** [comment]
Hi @mbbroberg, 
Thanks for reporting the error.
The list is now at: https://github.com/chaoss/metrics/#full-list-of-activity-metrics

You can change everything about the metric. The sentence just means we want it to match afterwards.

**Comment by mbbroberg** [comment]
Thanks @GeorgLink! Closing as fixed by #175
