### ISSUE TITLE
Change Title to Diversity and Inclusion

### ISSUE THREAD

**Issue by germonprez** [chaoss/metrics#25]
Per the comments on the email list, we should discuss expanding the Diversity.md file to address inclusion as well.

**Comment by BenLloydPearson** [comment]
I think we could expand on it further and move contributor growth to be a part of this as well (and remove it from growth-maturity-decline). This would allow the growth-maturity-decline metrics to focus on the software side, while the diversity section focuses more on the human side of development. We could title it "Diversity, Inclusion, and Contributor Growth."

**Comment by germonprez** [comment]
I can certainly see this. 

#1
Move: Community Growth | Number of new developers over time
From: Growth-Maturity-Decline
To: Diversity & Inclusion

#2 
Rename: Diversity & Inclusion 
To: Diversity, Inclusion, and Contributor Growth

Regarding #2, what do you think about Diversity & Participation? Does that encompass what you are getting at -- without losing the message?

**Comment by BenLloydPearson** [comment]
> what do you think about Diversity & Participation? Does that encompass what you are getting at -- without losing the message?

I think that works pretty well, the only potential issue I can think of is if we want to designate a separation between user and contributor participation. Issue #21 mentions potentially creating a new metric related to user experience, so maybe we can designate this as Contributor Diversity, Inclusion, and Participation to leave room for user-related metrics under a different domain.

**Comment by germonprez** [comment]
In this case, what is the distinction between contributor and user? Is the user, the user of the OSS? 

I do very much like Contributor Diversity, Inclusion, and Participation

**Comment by BenLloydPearson** [comment]
> Is the user, the user of the OSS?

Precisely, I'm not sure how much there would be to track related to this, but it might be worthwhile to keep that separate from contributor metrics.

**Comment by germonprez** [comment]
Got it.

**Comment by jasontclark** [comment]
@germonprez Just to chime in on the discussion here, I would think that a contributor would be defined as a person who adds value (bug fixes, features, release engineering efforts) to the CHAOSS community projects, and a user is more-so a consumer/implementor of those projects.

**Comment by germonprez** [comment]
Fair enough, thanks @jasontclark
