### ISSUE TITLE
Diversity Pipeline

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/metrics#48]
Idea for a new metric: Diversity Pipeline

While attending the Open Source Summit Europe - diversity track, I scribbled down in my notes: "Diversity Pipeline - of organizations with multiple community members, what is the diversity of the organization's representation within the community?"

Today, I interpret this to show how well an organization is doing in using the diversity they have internally to represent themselves in open source communities. The idea is that if an organization has a gender diversity of 20% and are represented in an open source community with 5 men and 5 women, then their Diversity Pipeline metric is 50%/20% = 250% !!!

From a community perspective, this metric only applies to organizations that have multiple employees working on the same open source project. From an organization perspective, all employees engaged in open source could be considered and the Diversity Pipeline metric is not specific to an individual community.

Thoughts?

**Comment by germonprez** [comment]
I'm guessing this would be an activity metric. 

So the metric is not necessarily a reflection of the community. Is that right?

**Comment by GeorgLink** [comment]
​I am thinking of this as a diversity metric from an organizational
perspective. Only an organization can actually know what their internal
diversity which is required to calculate Diversitye Pipeline.

I don't see it as an activity metric, because it is only concerned with the
presence of people, not what they are actually doing.

**Comment by germonprez** [comment]
I'm not sold on it being its own first order metric. It doesn't seem to fit. Why would the presence of people be different from something like the presence of companies?

**Comment by germonprez** [comment]
What is the state of this? I'd love to close it :)

**Comment by GeorgLink** [comment]
​You can close it. It seems to not scratch any itches.

**Comment by germonprez** [comment]
:)
