### ISSUE TITLE
Why is the "bus factor" metric not in the risk category?

### ISSUE THREAD

**Issue by tobie** [chaoss/metrics#53]
It seems that a high bus factor is a large risk for a project.

**Comment by GeorgLink** [comment]
The answer is: No one has put it there. 
Feel free to create a pull request to suggest adding it.

**Comment by tobie** [comment]
I phrased that poorly, sorry. It's [already in the project](https://github.com/chaoss/metrics/search?utf8=%E2%9C%93&q=bus&type=) but not in the risk category.

I guess I'm confused about how the project structure is structured vs. how the repository is laid out.

**Comment by germonprez** [comment]
Thanks for getting this going @tobie. The project is still in a 'gather information' sort of phase. We have simply been recording where people put things. I think it is quite possible for an activity metric (like bus factor) to appear in several Metrics Categories. I can certainly see it in Risk and even in Growth-Maturity-Decline.
