### ISSUE TITLE
Describe path to maintainership

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/metrics#56]
We should describe a path to maintainership for the metrics repository and Metrics Committee.

This feeds into succession planning and inclusion efforts.

**Comment by GeorgLink** [comment]
referenced in chaoss/governance#5

**Comment by GeorgLink** [comment]
Define 'Path to Maintainership' and 'List Maintainers'
Per proposal in chaoss/governance#5 :

> The README.md of the repository contains a list of who is maintainer. Each CHAOSS repositry brings together different people and they document in the repository specific CONTRIBUTING.md how somone becomes a maintainer on their repository.

TODO:
- Specify 'path to maintainership' for this repo in CONTRIBUTING.md file
- List current maintainers in README.md file

**Comment by germonprez** [comment]
Thoughts on this... 

Is the question who has commit rights on the repo? If this is the case, I'd like to keep the number low for a few reasons. 

1) So that we know who the maintainers are
2) So that if you are in a role of maintainership, there isn't a 'someone else will merge' :)
3) We would graduate people off this role as we add new people. 

Perhaps we start with something to the effect of being on x number of reviews.

**Comment by GeorgLink** [comment]
This issue has two parts to it and you address both:

1. How does one become a maintainer?
- describe criteria and process

> - There will be x number of maintainers.
> - As we identify new maintainers, they will replace existing maintainers
> - Which maintainer steps down will be negotiated amongst maintainers
> - Someone who has done x reviews will be asked if they want to become a
maintainer.


2. Who are the current maintainers?
- this is not obvious from the GitHub interface
- we should list them in the README.md

> We need to provide an answer to the first part before addressing this
part.

**Comment by germonprez** [comment]
This works for me. Starting number? 3 (it's the magic number).

**Comment by GeorgLink** [comment]
3 is fine. I updated my previous comment

**Comment by GeorgLink** [comment]
We can review every quarter who should be a maintainer and whether we need to adjust the number of maintainers.

Maintainers are the ones responsible and capable for accepting pull requests.
