### ISSUE TITLE
Remove duplicate entries from list of metrics

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/metrics#61]
In the long metrics list, some metrics are identical with different names or have only slight variations. 

Issue first reported in #58

**Comment by germonprez** [comment]
Could you point out any that are duplicate? Or at least candidates?

**Comment by saloni-garg** [comment]
I had a look at the metrics table, and I found these metrics to be quite similar- 
- Total New Contributing Organizations
- New Contributing Organizations
- New Contributor Organizations

We can try to assemble them into 1 or 2, maybe? Just a suggestion.

**Comment by germonprez** [comment]
I have fixed this. I suggested keeping 

    Total New Contributing Organizations
    New Contributing Organizations

The latter is used by GMD and the former is a running total (as I see it). A bit different from identifying new organizations.
