### ISSUE TITLE
New to the open source  and your organisation

### ISSUE THREAD

**Issue by theexplorist** [chaoss/metrics#67]
I am new to the fascinating open source community .I have not attended any of your meetings but wish to contribute to your community.I know less time is remaining so kindly give me an overview and guidance.
Thank you.

**Comment by germonprez** [comment]
@theexplorist, If you are interested in participating in the GSoC through the CHAOSS project, you should visit the following links. They will give you a better idea of how we are proceeding.

https://wiki.linuxfoundation.org/chaoss/gsoc-ideas
https://lists.linuxfoundation.org/pipermail/oss-health-metrics/2018-February/000517.html

I suggest that you participate directly in the GitHub repositories to which you are hoping to work.

**Comment by GeorgLink** [comment]
GSoC applications are complete.
